#!/usr/bin/env python3

'''
Written by:
    Christopher Ahn
    Hee Woong Lim
Description:
    Print contents of pickle file generated by MPRAflow
    1. *_coords_to_barcodes.pickle
        Print a pair of ( CRS name, number of barcodes ) to STDIO
    2. *_barcode_counts.pickle:
        Print a pair of ( barcode, count ) to STDIO
'''

import pickle
import sys


def print_dict_value_len(pickle_file):
    ## Attempt to load the pickle file
    try:
        with open(pickle_file, 'rb') as f:
            data = pickle.load(f)
    except (pickle.UnpicklingError, EOFError, AttributeError, ValueError) as e:
        print(f"Error: input file is not a pickle file.")
        return

    ## loop through all keys
    for key, value in data.items():
        for bcd in value:
            print(f"{key}\t{bcd}")

## main
if __name__ == "__main__":
    ## check command line format
    if len(sys.argv) != 2:
        print("Usage: python mpra.print_crs_bcd_filtered.py.py <pickle_file>")
    else:
        pickle_file = sys.argv[1]
        print_dict_value_len(pickle_file)
